export let masterData = [
  {
    index: 1,
    college_name: "Indian Institute of Technology (IIT) Delhi",
    location: "Delhi",
    fees: "₹ 2.25 Lakhs",
    college_dunia_ranking: 1,
    user_review_rating: 4.8,
    rank: 1,
  },
  {
    index: 2,
    college_name: "Indian Institute of Technology (IIT) Bombay",
    location: "Mumbai",
    fees: "₹ 4.5 Lakhs",
    college_dunia_ranking: 2,
    user_review_rating: 4.7,
    rank: 2,
  },
  {
    index: 3,
    college_name: "Indian Institute of Technology (IIT) Madras",
    location: "Chennai",
    fees: "₹ 3.25 Lakhs",
    college_dunia_ranking: 3,
    user_review_rating: 4.6,
    rank: 3,
  },
  {
    index: 4,
    college_name: "Birla Institute of Technology and Science (BITS) Pilani",
    location: "Pilani",
    fees: "₹ 2.0 Lakhs",
    college_dunia_ranking: 4,
    user_review_rating: 4.5,
    rank: 4,
  },
  {
    index: 5,
    college_name: "College of Engineering, Pune (COEP)",
    location: "Pune",
    fees: "₹ 2.25 Lakhs",
    college_dunia_ranking: 5,
    user_review_rating: 4.4,
    rank: 5,
  },
  {
    index: 6,
    college_name: "Vellore Institute of Technology (VIT) University",
    location: "Vellore",
    fees: "₹ 3.08 Lakhs",
    college_dunia_ranking: 6,
    user_review_rating: 4.3,
    rank: 6,
  },
  {
    index: 7,
    college_name: "Indian Institute of Technology (IIT) Kanpur",
    location: "Kanpur",
    fees: "₹ 4.55 Lakhs",
    college_dunia_ranking: 7,
    user_review_rating: 4.2,
    rank: 7,
  },
  {
    index: 8,
    college_name: "Thapar Institute of Engineering and Technology",
    location: "Patiala",
    fees: "₹ 11.5 Lakhs",
    college_dunia_ranking: 8,
    user_review_rating: 4.1,
    rank: 8,
  },
  {
    index: 9,
    college_name: "Indian Institute of Technology (IIT) Kharagpur",
    location: "Kharagpur",
    fees: "₹ 7.2 Lakhs",
    college_dunia_ranking: 9,
    user_review_rating: 4.0,
    rank: 9,
  },
  {
    index: 10,
    college_name: "Netaji Subhas Institute of Technology (NSIT)",
    location: "Delhi",
    fees: "₹ 5.25 Lakhs",
    college_dunia_ranking: 10,
    user_review_rating: 3.9,
    rank: 10,
  },
  {
    index: 11,
    college_name: "Jadavpur University, Faculty of Engineering and Technology",
    location: "Kolkata",
    fees: "₹ 4.5 Lakhs",
    college_dunia_ranking: 11,
    user_review_rating: 3.8,
    rank: 11,
  },
  {
    index: 12,
    college_name: "Motilal Nehru National Institute of Technology (MNNIT)",
    location: "Allahabad",
    fees: "₹ 7.75 Lakhs",
    college_dunia_ranking: 12,
    user_review_rating: 3.7,
    rank: 12,
  },
  {
    index: 13,
    college_name: "National Institute of Technology (NIT) Warangal",
    location: "Warangal",
    fees: "₹ 3.5 Lakhs",
    college_dunia_ranking: 13,
    user_review_rating: 3.6,
    rank: 13,
  },
  {
    index: 14,
    college_name:
      "Indian Institute of Engineering Science and Technology (IIEST)",
    location: "Shibpur",
    fees: "₹ 3.75 Lakhs",
    college_dunia_ranking: 14,
    user_review_rating: 3.5,
    rank: 14,
  },
  {
    index: 15,
    college_name: "Indian Institute of Information Technology (IIIT) Hyderabad",
    location: "Hyderabad",
    fees: "₹ 3.80 Lakhs",
    college_dunia_ranking: 15,
    user_review_rating: 3.4,
    rank: 15,
  },
];
